server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sqlexam?serverTimezone=UTC
    username: root
    password: 1009
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      initial-size: 1 # 初始化大小
      min-idle: 1 # 最小等待连接数量
      max-active: 20 # 最大连接数
      max-wait: 86400 # 超时设置
      min-evictable-idle-time-millis: 30000 # 最小空闲时间
      max-evictable-idle-time-millis: 60000 # 最大空闲时间
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
  http:
    converters:
      preferred-json-mapper: gson # 强制使用Gson

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
  mapper-locations: classpath:com/example/mapper/*.xml/
  type-aliases-package: com.example.workflowcli.*.domain # 实体扫描
  global-config:
    db-config:
      table-underline: true
flowable:
  db-history-used: true
  history-level: audit
  database-schema-update: true # 表更新
  check-process-definitions: true # 流程定义
  async-executor-activate: false # 关闭定时任务JOB
  deployment-name: SpringBootAutoDeployment # 自动部署的名称
  process-definition-location-prefix: classpath*:/processes/ # 自动部署时查找流程的目录
  #  label-font-name: 宋体
  #  annotation-font-name: 宋体
  #  activity-font-name: 宋体