server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sqlexam?serverTimezone=UTC
    username: root
    password: 1009
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      # 初始化大小
      initial-size: 1
      # 最小等待连接数量
      min-idle: 1
      # 最大连接数
      max-active: 20
      # 超时设置
      max-wait: 86400
      # 空闲时间
      min-evictable-idle-time-millis: 30000
#      max-evictable-idle-time-millis: 60000
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/static/stencilset
  http:
    converters:
      # 强制使用Gson
      preferred-json-mapper: gson

mybatis-plus:
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/example/mapper/*.xml/
  # 实体扫描
  type-aliases-package: com.example.workflowcli.*.domain
  global-config:
    db-config:
      table-underline: true
flowable:
  # 历史级别
  history-level: audit
  # 启用历史表
  db-history-used: true
  # 表更新策略: 开发环境改为true;生产环境改为false
  database-schema-update: true
  # 关闭定时任务JOB
  async-executor-activate: false
  # 流程定义
  check-process-definitions: true
  # 自动部署的名称
  deployment-name: SpringBootAutoDeployment
  # 自动部署时查找流程的目录
  process-definition-location-prefix: classpath*:/processes/
  # 解决中文乱码
  label-font-name: 宋体
  annotation-font-name: 宋体
  activity-font-name: 宋体