server:
  port: 8888
  max-http-header-size: 4096
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 1009
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      #初始化大小
      initial-size: 1
      #最小等待连接数量
      min-idle: 1
      #最大连接数
      max-active: 20
      #超时设置
      max-wait: 86400
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/flowable-modeler
  #  强制使用Gson
  http:
    converters:
      preferred-json-mapper: gson


mybatis-plus:
  mapper-locations: classpath:/com/example/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
flowable:
  async-executor-activate: false # 关闭定时任务JOB
  database-schema-update: false # 建表策略,第一次运行是改为true,之后改为false
  check-process-definitions: true # 启用自动部署流程定义
  db-history-used: true # 启用db历史表
  history-level: audit # 要使用的历史级别。
  deployment-name: SpringBootAutoDeployment # 自动部署的名称
  process-definition-location-prefix: classpath*:/processes/ # 自动部署时查找流程的目录
  label-font-name: 宋体
  annotation-font-name: 宋体
  activity-font-name: 宋体
